// see http://plantuml.sourceforge.net/skinparam.html

@startuml

skinparam backgroundColor #FFFFFF
skinparam activity {
  BackgroundColor #ECECFF
  BorderColor #000CCF
  ArrowColor #808080
  FontName Arial
}

@enduml
